.storybook/addons.js
.storybook/config.js
package-lock.json
package.json

Remember to `npm install` then restart Storybook .  
- Added storybook addon-options
- Moved storybook infopanel to right .

Storybook Addon-Options

---

package-lock.json
package.json

feat: add storybook-deployer

---

README.md

feat: new Badges proving our awesome

---

package-lock.json
package.json

Resolves #41 
Added tooling to update dependencies similar to gm-fabric-dashboard.

feat: add ncu to simplify dep updates

---

src/components/AppFooter/AppFooter.js
src/components/AppFooter/AppFooter.spec.js
src/components/AppFooter/__snapshots__/AppFooter.spec.js.snap
src/components/AppFooter/index.js
src/components/Button/components/ButtonWrap/ButtonWrap.js
src/components/Button/components/ButtonWrap/utils/generateButtonSize.js
src/components/Footer/index.js
src/components/index.js
src/stories/AppFooter.story.js
src/stories/Button.story.js
src/stories/index.js

Rename “Footer” to “AppFooter”

Minor fixes

---

package-lock.json
package.json

feat: add commitlint

---

src/components/Breadcrumbs/Breadcrumbs.js
src/components/Breadcrumbs/Breadcrumbs.stories.js

fix: pass through props to breadcrumbs container

---

package-lock.json
src/components/Tab/__snapshots__/Tab.test.js.snap
src/components/Tab/components/TabWrap.js
src/components/TabGroup/__snapshots__/TabGroup.test.js.snap
src/components/TabGroup/components/TabGroupLabel.js

feat: update Tab styles

---

src/components/Button/Button.js

fix: only render label span if label is a non-empty string

---

src/components/Breadcrumbs/BreadcrumbItem.js
src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap

fix: remove hard-coded color property from breadcrumbs styles

---

src/components/Readout/Readout.js
src/components/Readout/Readout.stories.js
src/components/Readout/components/ReadoutItem/components/ItemDisplay.js
src/components/Readout/components/ReadoutItem/components/ItemDisplay.test.js
src/components/Readout/components/ReadoutItem/components/__snapshots__/ItemDisplay.test.js.snap
src/components/Readout/components/ReadoutItem/components/__snapshots__/ReadoutItemValue.test.js.snap
src/components/Readout/components/__snapshots__/ReadoutDisplay.test.js.snap
src/components/Tab/__snapshots__/Tab.test.js.snap
src/components/TabGroup/__snapshots__/TabGroup.test.js.snap
src/style/styleVariables.js

- updated a few style variables so we're more in line with dashboard
- cleaned up ItemDisplay.js which wasn't really doing anything with its props

fix: readout styles

---

src/components/ErrorCard/ErrorCard.js
src/components/ErrorCard/ErrorCard.stories.js
src/components/ErrorCard/ErrorCard.test.js
src/components/ErrorCard/__snapshots__/ErrorCard.test.js.snap
src/components/ErrorCard/components/ErrorBox.js
src/components/ErrorCard/components/ErrorBox.test.js
src/components/ErrorCard/components/ErrorContent.js
src/components/ErrorCard/components/ErrorContent.test.js
src/components/ErrorCard/components/Span.js
src/components/ErrorCard/components/Span.test.js
src/components/ErrorCard/components/__snapshots__/ErrorBox.test.js.snap
src/components/ErrorCard/components/__snapshots__/ErrorContent.test.js.snap
src/components/ErrorCard/components/__snapshots__/Span.test.js.snap
src/components/ErrorCard/index.js
src/components/index.js

feat: add ErrorCard

---

src/components/Input/Input.js
src/components/Input/Input.stories.js
src/components/Input/Input.test.js
src/components/Input/__snapshots__/Input.test.js.snap
src/components/Input/index.js
src/components/index.js

fix: update Input styles

---

src/components/AppFooter/AppFooter.js
src/components/AppHeader/AppHeader.js
src/components/AppHeader/AppHeader.test.js
src/components/AppHeader/__snapshots__/AppHeader.test.js.snap
src/components/Button/Button.js
src/components/ErrorCard/ErrorCard.js
src/components/LayoutSection/LayoutSection.js
src/components/NavCard/NavCard.js
src/components/Tab/Tab.js
src/components/TabGroup/TabGroup.js
src/components/Tooltip/Tooltip.js

Resolves #221 
Resolves #220 
Resolves #215

fix: pass through props to styled-components

---

src/components/AppFooter/__snapshots__/AppFooter.test.js.snap
src/components/AppFooter/components/Footer.js
src/components/AppFooter/components/Link.js
src/components/AppFooter/components/Links.js
src/components/AppFooter/components/LongLogo.js
src/components/AppFooter/components/__snapshots__/Footer.test.js.snap
src/components/AppFooter/components/__snapshots__/Link.test.js.snap
src/components/AppFooter/components/__snapshots__/Links.test.js.snap
src/components/AppFooter/components/__snapshots__/LongLogo.test.js.snap

- Better (smaller) logo size
- Tighter spacing for off-site links
- Solid background

feat: cleaner app footer

---

src/components/NavCardGroup/NavCardGroup.js
src/components/NavCardGroup/__snapshots__/NavCardGroup.test.js.snap

style: remove unused css property from NavCardGroup

---

src/components/Table/Table.js
src/components/Table/Table.stories.js
src/components/Table/Table.test.js
src/components/Table/__snapshots__/Table.test.js.snap
src/components/Table/components/TableCell.js
src/components/Table/components/TableColumn.js
src/components/Table/components/TableHeader.js
src/components/Table/components/TableRow.js
src/components/Table/components/TableWrapper.js
src/components/Table/components/tests/TableCell.test.js
src/components/Table/components/tests/TableColumn.test.js
src/components/Table/components/tests/TableHeader.test.js
src/components/Table/components/tests/TableRow.test.js
src/components/Table/components/tests/TableWrapper.test.js
src/components/Table/components/tests/__snapshots__/TableCell.test.js.snap
src/components/Table/components/tests/__snapshots__/TableColumn.test.js.snap
src/components/Table/components/tests/__snapshots__/TableHeader.test.js.snap
src/components/Table/components/tests/__snapshots__/TableRow.test.js.snap
src/components/Table/components/tests/__snapshots__/TableWrapper.test.js.snap
src/components/Table/types.js
src/components/index.js

feat: added Table component

---

src/components/Input/components/InputField.js
src/components/Input/components/__snapshots__/InputField.test.js.snap

- Adds default `COLOR_BACKGROUND_A` to input field

fix: adding missing background color for inputs

---

src/components/Tooltip/Tooltip.stories.js
src/components/Tooltip/__snapshots__/Tooltip.test.js.snap
src/components/Tooltip/components/TooltipWrap.js

fix: remove ? cursor from tooltip

---

src/components/Form/scenes/Radio/Radio.stories.js

- Adds withInfo bits to Radio component
- Minor changes to labels and stories

feat: minor improvements to radio button story

---

package.json
src/components/Form/components/Fieldset/Fieldset.js
src/components/Form/components/Fieldset/__snapshots__/Fieldset.test.js.snap
src/components/Form/components/InputHint.js
src/components/Form/components/InputWrap.js
src/components/Form/scenes/Radio/__snapshots__/Radio.test.js.snap
src/components/Form/scenes/Select/__snapshots__/Select.test.js.snap
src/components/NavCard/components/NavCardWrapper.js
src/components/NavCard/components/__snapshots__/NavCardWrapper.test.js.snap

I was very conservative about this - let me know if you think there are other components that qualify.

fix: remove external margins

---

src/components/AppFooter/AppFooter.js
src/components/AppFooter/AppFooter.stories.js
src/components/AppFooter/AppFooter.test.js
src/components/AppFooter/components/Copyright.js
src/components/AppFooter/components/__snapshots__/Copyright.test.js.snap

feat: add ability to disable external links in the footer

---

.storybook/addons.js
.storybook/config.js
package-lock.json
package.json
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Button/components/ButtonWrap/ButtonWrap.js
src/components/Button/components/ButtonWrap/__snapshots__/ButtonWrap.test.js.snap
src/components/Form/components/InputBox.js
src/components/Form/components/InputFieldInteractionStyles.js
src/components/Form/scenes/Checkbox/components/CheckboxBox.js
src/components/Form/scenes/InputRange/components/InputRangeControl.js
src/components/Form/scenes/Radio/components/RadioBox.js
src/components/Spinner/Spinner.js
src/components/Spinner/Spinner.test.js
src/components/Spinner/__snapshots__/Spinner.test.js.snap
src/components/Spinner/components/LoadingSpinner.js
src/components/Spinner/components/LoadingSpinner.test.js
src/components/Spinner/components/__snapshots__/LoadingSpinner.test.js.snap
src/components/Tab/components/TabWrap.js
src/components/Table/Table.js
src/components/Table/components/TableRow.js
src/components/Table/components/tests/__snapshots__/TableRow.test.js.snap

- updated all instances of brand_color and color_intent_highlight to use theme first
- added a theme decorator to storybook
`npm i && npm start` and play around with the theme tab

feat: theme brand color

---

CHANGELOG.md
package-lock.json
package.json

chore: manually cleanup changelog

chore: updated version to v0.7.2

---

src/components/Tooltip/components/TooltipContent.js

- Follow contributing guide instructions to `npm link` this to the dashboard. 
- Test the fabric view & configuration view

fix: tooltip visibility issue

---

src/components/AppFooter/AppFooter.js
src/components/AppFooter/__snapshots__/AppFooter.test.js.snap
src/components/AppFooter/components/Copyright.js
src/components/AppFooter/components/__snapshots__/Copyright.test.js.snap

`npm start`
View AppFooter in storybook

fix: update footer font size and default text

---

src/components/index.js
webpack.config.js

to test
- follow [instructions in contributing](https://github.com/DecipherNow/gm-ui-components/blob/master/CONTRIBUTING.md#develop-using-a-linked-app) to `npm link` to your app 
- import style variables, functions, and confirm everything works as expected

feat: export style variables and functions

---

src/components/Button/Button.js
src/components/Button/Button.stories.js
src/components/Button/__snapshots__/Button.test.js.snap
src/components/Button/components/ButtonWrap/ButtonWrap.js
src/components/Button/components/ButtonWrap/utils/generateButtonStyle.js

- Add 'dangerouslySetColor' prop to Buttons
- set default button Type to 'default' instead of null

feat: add prop to buttons to allow custom color

---

src/style/themes.stories.js

Adds theme story for a bit of theme debugging and demonstration
After:

feat: add theme story

---

src/components/Tab/components/TabWrap.js
src/components/Table/components/TableRow.js

fix: replace brand color with highlight color

---

src/components/Button/Button.js

- Removes vestigial 'secondary' type from Button component
Closes #434

fix: remove unused secondary typefrom button

---

src/components/Form/components/InputLabelText.js
src/components/Form/components/__snapshots__/InputLabelText.test.js.snap
src/components/Form/components/__snapshots__/InputWrap.test.js.snap
src/components/Form/scenes/Checkbox/Checkbox.stories.js
src/components/Form/scenes/InputField/InputField.stories.js
src/components/Form/scenes/InputRange/InputRange.stories.js

Adds Typical use stories for Checkbox, InputField, and InputRange.

fix: add missing stories

---

src/components/Checkbox/Checkbox.js

- Removes `defaultChecked` prop from Checkbox component.
Closes #520

refactor: remove defaultChecked prop

---

.storybook/addons.js
.storybook/config.js
package-lock.json
package.json

- Adds `a11y` add-on to give feedback on accessibility.

feat: install a11y addon

---

package-lock.json
package.json

- Adds `focus-visible` package, in preparation for future UX/style improvements to interactive components.

feat: add focus-visible

---

config/template.js
package-lock.json
src/components/Spinner/Spinner.js
src/components/Tooltip/Tooltip.js
src/components/Tooltip/__snapshots__/Tooltip.test.js.snap

- add memoization to svg's
- optimize tooltip

feat: performance enhancements

---

config/template.js

fix: icon displayName

---

src/components/Breadcrumbs/Breadcrumbs.js
src/components/Breadcrumbs/Breadcrumbs.stories.js
src/components/Icon/Icon.js

Fixes formatting for files that were committed via Github suggestions

chore: fix formatting

---

package-lock.json
src/components/Icon/Icon.js
src/style/themes.stories.js

Closes #611
- removed odd background colors behind fieldsets in theme story
- updated Icon deprecation warning so users know warning is coming from this library

small tweaks

---

LICENSE

Story details: https://app.shortcut.com/grey-matter/story/18945

chore: [sc-18945] Review all copyright messages in source code and make sure they are greymatter.io, not Decipher.
