greymatter-io/gm-ui-components

package.json
`preversion` script that runs tests and only bumps the version if they pass
`postpublish` script that deploys storybook
I'm thinking that once the changelog script is merged in I can add that to a `postversion` script
=> WIP chore: add version and publish scripts

src/components/Button/Button.js, src/components/Button/Button.test.js, src/components/Button/components/ButtonWrap/ButtonWrap.js, src/components/ButtonGroup/ButtonGroup.js, src/components/ButtonGroup/ButtonGroup.test.js, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap, src/components/ButtonGroup/index.js, src/components/index.js, src/stories/Button.story.js, src/stories/ButtonGroup.story.js, src/stories/index.js
- It turns out we had both an iconSize and glyphRatio prop for our button, which was part of the confusion. I got rid of glyphRatio and correctly implemented iconSize. Now we can independently control button size and the glyph size, and they'll actually work together.
- Renamed `iconSize` to `glyphSize`, since that made more sense to me in the context of our other props.
- Added tests, storybook
=> feat: add ButtonGroup

src/components/AppFooter/__snapshots__/AppFooter.test.js.snap, src/components/AppFooter/components/__snapshots__/Footer.test.js.snap, src/style/styleVariables.js
AppFooter was using ZINDEX_STICKY, but that was not in our styleVariables
=> fix: add missing ZINDEX_STICKY

src/components/Spinner/Spinner.js, src/components/Spinner/Spinner.stories.js, src/components/Spinner/Spinner.test.js, src/components/Spinner/__snapshots__/Spinner.test.js.snap, src/components/Spinner/components/Rotate360.js, src/components/Spinner/index.js, src/components/index.js
I propose that we add the spinner from `gm-fabric-dashboard`. It's pretty general purpose and seems like something that should be generally consistent across UIs.
=> feat: add spinner

src/components/Breadcrumbs/BreadcrumbItem.js, src/components/Breadcrumbs/Breadcrumbs.js, src/components/Breadcrumbs/Breadcrumbs.stories.js, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap
Resolves #186 
- cleaned up styles
- made the crumbs responsive, so they will fit the parent container
- added an internal prop, `hideDelimiter`, that hides the > when there is only one item
=> fix: clean up styles, responsiveness, & hide delimiter when there is only one item

src/components/LayoutSection/LayoutSection.stories.js, src/components/NavCard/NavCard.stories.js, src/components/NavCard/components/NavCardWrapper.js, src/components/NavCard/components/__snapshots__/NavCardWrapper.test.js.snap, src/components/NavCardGroup/NavCardGroup.js, src/components/NavCardGroup/__snapshots__/NavCardGroup.test.js.snap, src/components/Readout/Readout.stories.js, src/components/Readout/components/ReadoutItem/ReadoutItem.test.js
This was a little tricky, because we're expecting NavCard to be wrapped in a link element by the end user, so NavCard is no longer the direct child of NavCardGroup. That means we need to style the link elements from NavCardGroup. I tried to add comments to clarify the css.
=> fix: cleanup NavCard and NavCardGroup styles

src/components/AppHeader/AppHeader.stories.js, src/components/AppHeader/components/HeaderWrapper.js, src/components/AppHeader/components/__snapshots__/HeaderWrapper.test.js.snap, src/components/Breadcrumbs/BreadcrumbItem.js, src/components/Breadcrumbs/Breadcrumbs.js, src/components/Breadcrumbs/Breadcrumbs.stories.js, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap
Resolves #222 
- added a `collapse` prop for finer control
- added `flex-wrap: wrap;` to the Breadcrumb wrapper so that items flow onto a new line
- cleaned up breadcrumb and appheader stories
=> fix: breadcrumb responsiveness

src/components/AppHeader/AppHeader.stories.js
The breadcrumbs prop is obsolete now that we pass the toolbarItems render prop
=> fix: remove breadcrumbs from AppHeader story

src/components/Table/Table.js, src/components/Table/__snapshots__/Table.test.js.snap, src/components/Table/components/TableRow.js, src/components/Table/components/tests/__snapshots__/TableRow.test.js.snap
Since the library is moving away from being a product-only tool, we should offer a color prop so that the consuming app can specify it's own brand color. Defaults to decipher brand color.
=> feat: add accentColor prop to table

src/components/Table/Table.js, src/components/Table/Table.stories.js, src/components/Table/components/TableRow.js
When I was trying to modify this component for the workspaces table in data-ui, I realized that I couldn't edit the selected row styles. this pr adds a hook so that you can pass inline styles, or styled-component `css`` `
=> fix: add styleSelectedRow prop

src/components/Button/__snapshots__/Button.test.js.snap, src/components/Button/components/ButtonWrap/ButtonWrap.js, src/components/Button/components/ButtonWrap/__snapshots__/ButtonWrap.test.js.snap
- Bringing the font weight of buttons back to the regular weight.
Higher weight makes buttons look odd in about 50% of uses, and in such a case I'd rather keep them unopinionated, rather than having to override a style later.
=> feat: less opinionated button styles

src/components/Icon/components/StyledSVG.js, src/components/Icon/components/__snapshots__/StyledSVG.test.js.snap
- Default size for icons now `1.714em` instead of as large as possible, `100%`.
=> feat: better default size for icons

src/components/Input/Input.js, src/components/Input/Input.stories.js, src/components/Input/components/InputField.js
This PR adds camelCasing to the Input components's `autoFocus` prop.  It was breaking tests in the dashboard.
```
FAIL  src/components/Main/components/MainContent/scenes/ServiceView/scenes/ServiceConfigurationView/components/ObjectivesForm/ObjectivesForm.test.js
● Objectives Form › matches snapshot
Error: Uncaught [Error: Warning: Invalid DOM property `autofocus`. Did you mean `autoFocus`?
in input (created by InputField)
```
=> fix: camel case Input component autoFocus prop

package-lock.json, src/components/Spinner/Spinner.test.js, src/components/Spinner/__snapshots__/Spinner.test.js.snap, src/components/Spinner/components/LoadingSpinner.js, src/components/Spinner/components/__snapshots__/LoadingSpinner.test.js.snap
Inherit theme through the styled-components class vs the withTheme() HOC to avoid a bug in production
- Use `npm link` to link the component library to the dashboard ([see these instructions](https://github.com/DecipherNow/gm-ui-components/blob/master/CONTRIBUTING.md#npm-link))
- In the dashboard run: `npm run build && open build/index.html`
- Confirm that the app loads and these errors are no longer in the console:
=> fix: refactor LoadingSpinner

package-lock.json, package.json, src/components/Tooltip/Tooltip.js, src/components/Tooltip/Tooltip.stories.js, src/components/Tooltip/Tooltip.test.js, src/components/Tooltip/__snapshots__/Tooltip.test.js.snap, src/components/Tooltip/components/TooltipContent.js, src/components/Tooltip/components/TooltipWrap.js
To test
- `npm install`, view Tooltip in storybook and play with props
- `npm link && npm run build -- --watch`
- In the dashboard, run `npm link gm-ui-components && npm run start:proxy` linking will NOT work in the dc environment
=> refactor: use react-popper positioning engine with tooltip

src/components/Readout/Readout.js, src/components/Readout/Readout.stories.js, src/components/Readout/__snapshots__/Readout.test.js.snap, src/components/index.js
- pass color prop to ReadoutDisplay
- export keen and keenDark from the lib so people can use them and extend the defaults
to test
- `npm start` and check readout styles, change the color knob
=> fix: readout styles, add missing theme exports

src/ComponentLibrary/StoryComponents/StoryContainer.js
- Fix dark theme background appearing to stretch beyond the component box area.
Before:
After:
=> fix: fix theme background color applying to entire storycontainer

src/style/GlobalStyles.js
`a:link` had unintended consequences over `a`, including breaking AppFooter link colors.
It’s preferable to make fewer assumptions at the global level than to force more overrides down the tree.
=> fix: lower global link style specificity

src/components/Button/__snapshots__/Button.test.js.snap, src/components/Button/components/ButtonWrap/utils/generateButtonSize.js, src/components/Button/components/ButtonWrap/utils/generateButtonSize.test.js
Closes #474 
Before: 
```xs: 9px
sm: 11px
normal: 14px
lg: 18px
xl: 18px
```
After: 
```xs: 9px
sm: 11px
normal: 14px
lg: 16px
xl: 18px
```
=> fix: make button size generator use proper font sizes

.storybook/config.js, package-lock.json, package.json, src/components/Button/Button.stories.js, src/components/Tooltip/components/TooltipContent.js
Closes #469
- Add `withPropsCombinations` function to Button stories to demonstrate component props.
After:
=> feat: show all props gallery for button component

src/components/Checkbox/Checkbox.js, src/components/Checkbox/Checkbox.stories.js
it is necessary to be able to set checkboxes as controlled components
=> feat: added additional prop checked to checkbox

src/components/index.js
This PR exports input utility functions so consumers of the library can style edge case inputs.
=> chore: export input util components

src/components/Collapse/Collapse.js, src/components/Collapse/__snapshots__/Collapse.test.js.snap, src/components/Collapse/components/Wrapper.js, src/components/Collapse/components/__snapshots__/index.test.js.snap
I removed some options that I thought were unnecessary from the mutation observer, but obviously they weren't!
To test:
- run storybook
- link to the dashboard if you want and test the route slos
=> fix: add options back to observer

package.json
Update NPM registry to show license as MIT.
Issue #527
=> chore: npm package license match license

src/components/Breadcrumbs/Breadcrumbs.js, src/components/Breadcrumbs/Breadcrumbs.test.js, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap
Proposed Changes
- set visibility hidden when hideDelimiter is true
- add test
To Test
- run storybook and confirm that hideDelimiter knob actually hides the delimiter
=> fix: hide delimiter prop

src/components/Tab/Tab.js, src/components/Tab/Tab.stories.js, src/components/Tab/__snapshots__/Tab.test.js.snap, src/components/Tab/components/TabWrap.js, src/components/TabGroup/__snapshots__/TabGroup.test.js.snap
Fixes #537
- Removes unnecessary explicit `disabled` prop from Tab component.
=> fix: remove explicit disabled prop from tabwrap

src/components/Tab/Tab.stories.js, src/components/Tab/__snapshots__/Tab.test.js.snap, src/components/Tab/components/TabWrap.js, src/components/TabGroup/TabGroup.stories.js, src/components/TabGroup/__snapshots__/TabGroup.test.js.snap
- Adds focus styles to tabs
- Tabs no longer transition the size of their highlight, only the opacity. This makes for a smoother transition and a cleaner appearance.
=> feat: tab focus styles and polish

CHANGELOG.md, package-lock.json, package.json
FYI the easiest way to test this in the dashboard now is using npm pack. In case it’s helpful my workflow is
1. npm run build && npm pack
2. in the dashboard, npm uninstall gm-ui-components && npm install <path-to-generated-tarball>
3. npm start (edited)
=> feat: release/1.3.0

README.md, package-lock.json, package.json
Removed outdated `Related Projects` from README and updated keywords in package.json. Both are improvements to what we're seeing in NPM.
=> chore: minor project changes

src/components/Badge/Badge.js, src/components/Badge/Badge.stories.js, src/components/Badge/index.js
closes #281 
- add badge component from [dashboard](https://github.com/DecipherNow/gm-dashboard/blob/release-3.5/src/style/components/Badge.js#L1)
=> feat: added badge component

src/components/Spinner/components/LoadingMessage.js, src/components/Spinner/components/__snapshots__/LoadingMessage.test.js.snap
Centers the loading message under the spinner.
=> fix: center spinner loading message

package-lock.json, package.json
We were missing `inter-ui` as a dev dependency which was breaking local development. I also changed the peerDependencies to major versions as that allows consumers of the package to choose any range of minor and patch versions. I tested using `npm pack` and installed in the dashboard to confirm everything continued to work.
=> fix: add inter as a dev dep and set peer deps to major versions only

src/components/Button/__snapshots__/Button.test.js.snap, src/components/Button/components/ButtonWrap/__snapshots__/ButtonWrap.test.js.snap, src/components/Button/components/ButtonWrap/utils/generateButtonStyle.js
Buttons use a white or black version of the theme's default content color, rather than a pure white or black.
This solves the issue where buttons always had a stronger text color than their surroundings. Buttons should be distinct and contrast with their surroundings, but not necessarily in this way, and not with this arbitrary restriction.
=> fix: solve cause of buttons having too-solid text color

src/components/Breadcrumbs/Breadcrumbs.js, src/components/Breadcrumbs/Breadcrumbs.stories.js, src/components/Breadcrumbs/Breadcrumbs.test.js, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.js.snap
Main point of this update was to replace the font character-based delimiter with an icon, so we have more control over the sizing and presentation. 
**Before:**
**After:**
Along the way, we also get a nicer way to add custom delimiters using any element passed into the `delimiter` prop, and a simple way to disable the delimiter with `delimiter={false}`.
=> better default breadcrumb delimiter (or custom, or none)

.circleci/config.yml, README.md
1. Removed CC_TEST_REPORTER_ID from source control and added it to CircleCI because we don't want to leak the ID. I also regenerated the ID, so the one that's currently in commit history will be invalid.
2. Removed david-dm as a 3rd party dependency tracker as we seldomnly use it and we receive security alerts from GitHub directly. Not to mention, that https://david-dm.org/ doesn't seem to be up anyways.
=> Project config

src/components/Icon/components/StyledSVG.js, src/components/Icon/components/__snapshots__/StyledSVG.test.js.snap
Sometimes icons need to be allowed to be squished relative to their viewbox. This fix ensures the icons themselves remain centered when that occurs, rather than falling to the "bottom" of the viewbox.
=> feat: squished icons remain centered

src/style/GlobalStyles.js
Map over the actual theme variables to generate the CSS vars, rather than hardcoding them.
=> feat: auto-generate css vars from theme vars

src/components/InputField/InputField.js, src/components/InputField/InputField.stories.js, src/components/InputField/__snapshots__/InputField.test.js.snap, src/components/util/InputReset.js, src/components/util/InputTextField.js, src/components/util/InputWrap.js, src/components/util/__snapshots__/InputTextField.test.js.snap
This PR adds cross-browser input reset functionality for `text` and `search` inputs.
How to test:
1. `npm start` and smoke test InputField via storybook
2. Test with an app following https://github.com/greymatter-io/gm-ui-components/blob/main/CONTRIBUTING.md#npm-pack
=> feat: add cross-browser input reset

CHANGELOG.md, package-lock.json, package.json
[sc-18596] Cut release of gm ui components 
Created a new release with changes to the footers logo image and copyright.
When I try to link this with my gm-dashboard 6.0.2 branch, I get this error in the dashboard:
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.`
and when I try to link it with the current 'main' branch of gm-dashboard, I don't see any changes in the footer, specifically the logo image, seeing as …
=> chore: Cut release of gm ui components 
